config/routes.rb
Rails.application.routes.draw do
  resources :temperatures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'temperatures#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/temperature.rb
class Temperature < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception  
  protect_from_forgery unless: -> { request.format.json? }  
end

app/controllers/temperatures_controller.rb
class TemperaturesController < ApplicationController
  before_action :set_temperature, only: [:show, :edit, :update, :destroy]

  # GET /temperatures
  # GET /temperatures.json
  def index
    @temperatures = Temperature.all
  end

  # GET /temperatures/1
  # GET /temperatures/1.json
  def show
    render json: @temperature
  end

  # GET /temperatures/new
  def new
    @temperature = Temperature.new
  end

  # GET /temperatures/1/edit
  def edit
  end

  # POST /temperatures
  # POST /temperatures.json
  def create
    @temperature = Temperature.new(temperature_params)

    respond_to do |format|
      if @temperature.save
        format.html { redirect_to @temperature, notice: 'Temperature was successfully created.' }
        format.json { render :show, status: :created, location: @temperature }
      else
        format.html { render :new }
        format.json { render json: @temperature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temperatures/1
  # PATCH/PUT /temperatures/1.json
  def update
    respond_to do |format|
      if @temperature.update(temperature_params)
        format.html { redirect_to @temperature, notice: 'Temperature was successfully updated.' }
        format.json { render :show, status: :ok, location: @temperature }
      else
        format.html { render :edit }
        format.json { render json: @temperature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temperatures/1
  # DELETE /temperatures/1.json
  def destroy
    @temperature.destroy
    respond_to do |format|
      format.html { redirect_to temperatures_url, notice: 'Temperature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_temperature
      @temperature = Temperature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def temperature_params
      params.require(:temperature).permit(:sensor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/temperatures_helper.rb
module TemperaturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TempControl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/temperatures/_form.html.erb
<%= form_with(model: temperature, local: true) do |form| %>
  <% if temperature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(temperature.errors.count, "error") %> prohibited this temperature from being saved:</h2>

      <ul>
      <% temperature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sensor %>
    <%= form.text_field :sensor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/temperatures/edit.html.erb
<h1>Editing Temperature</h1>

<%= render 'form', temperature: @temperature %>

<%= link_to 'Show', @temperature %> |
<%= link_to 'Back', temperatures_path %>

app/views/temperatures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Temperatures</h1>

<table>
  <thead>
    <tr>
      <th>Sensor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temperatures.each do |temperature| %>
      <tr>
        <td><%= temperature.sensor %></td>
        <td><%= link_to 'Show', temperature %></td>
        <td><%= link_to 'Edit', edit_temperature_path(temperature) %></td>
        <td><%= link_to 'Destroy', temperature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Temperature', new_temperature_path %>

app/views/temperatures/new.html.erb
<h1>New Temperature</h1>

<%= render 'form', temperature: @temperature %>

<%= link_to 'Back', temperatures_path %>

app/views/temperatures/show.html.erb
[
  {
    "postId": 7,
    "id": 31,
    "name": "ex velit ut cum eius odio ad placeat",
    "email": "Buford@shaylee.biz",
    "body": "quia incidunt ut\naliquid est ut rerum deleniti iure est\nipsum quia ea sint et\nvoluptatem quaerat eaque repudiandae eveniet aut"
  },
  {
    "postId": 7,
    "id": 32,
    "name": "dolorem architecto ut pariatur quae qui suscipit",
    "email": "Maria@laurel.name",
    "body": "nihil ea itaque libero illo\nofficiis quo quo dicta inventore consequatur voluptas voluptatem\ncorporis sed necessitatibus velit tempore\nrerum velit et temporibus"
  },
  {
    "postId": 7,
    "id": 33,
    "name": "voluptatum totam vel voluptate omnis",
    "email": "Jaeden.Towne@arlene.tv",
    "body": "fugit harum quae vero\nlibero unde tempore\nsoluta eaque culpa sequi quibusdam nulla id\net et necessitatibus"
  },
  {
    "postId": 7,
    "id": 34,
    "name": "omnis nemo sunt ab autem",
    "email": "Ethelyn.Schneider@emelia.co.uk",
    "body": "omnis temporibus quasi ab omnis\nfacilis et omnis illum quae quasi aut\nminus iure ex rem ut reprehenderit\nin non fugit"
  },
  {
    "postId": 7,
    "id": 35,
    "name": "repellendus sapiente omnis praesentium aliquam ipsum id molestiae omnis",
    "email": "Georgianna@florence.io",
    "body": "dolor mollitia quidem facere et\nvel est ut\nut repudiandae est quidem dolorem sed atque\nrem quia aut adipisci sunt"
  }
]